# Proyecto: Concatenación de tablas con Numpy y Pandas

## Obs: Para concatenar arrgelos o dataframes, estos deben ser de la misma dimensión


### En este proyecto veremos algunas funciones como:
`.randn()` <- Genera números aleatorios entre (-1,1)

`.rand()` <- Genera números aleatorios entre (0,1)

`np.concatenate([x1, x2], axis=0)` <- concatena 2 arreglos con numpy en dirección vertical

`pd.concat([x1, x2], axis=0)` <- concatena 2 Series o DataFrames con pandas en dirección vertical

`np.concatenate([x1, x2], axis=1)` <- concatena 2 arreglos con numpy en dirección horizontal

`pd.concat([x1, x2], axis=1)`  <- concatena 2 Series o DataFrames con pandas en dirección horizontal

`.reset_index(drop=True)` <- resetea los nombres de los indices

`.append()` <- Concatena 2 dataframes en dirección vertical


In [1]:
import numpy as np 

import pandas as pd

In [2]:
# Mostramos los valores con 2 decimales y sin notación científica:
pd.options.display.float_format = '{:,.2f}'.format

np.set_printoptions(precision=2)

## Concatenación de arreglos 2D con Numpy

In [3]:
# Genera numeros aleatorios en (-1 , 1)
np.random.randn()

0.16805534995829616

In [4]:
# Genera numeros aleatorios en (0 , 1)
np.random.rand()

0.95818502294037

In [5]:
x1 = np.random.rand(2,5)*10
x1

array([[5.96, 9.26, 5.02, 0.21, 1.45],
       [3.8 , 4.43, 2.92, 6.02, 9.11]])

In [6]:
x2 = np.random.rand(2,5)*(-1)
x2

array([[-0.34, -0.99, -0.75, -0.36, -0.82],
       [-0.92, -0.47, -0.6 , -1.  , -0.32]])

In [7]:
# Concatenamos verticalmente 2 matrices con numpy:
np.concatenate([x1, x2], axis=0)

array([[ 5.96,  9.26,  5.02,  0.21,  1.45],
       [ 3.8 ,  4.43,  2.92,  6.02,  9.11],
       [-0.34, -0.99, -0.75, -0.36, -0.82],
       [-0.92, -0.47, -0.6 , -1.  , -0.32]])

In [8]:
# Concatenamos horizontalmente 2 matrices con numpy:
np.concatenate([x1, x2], axis=1)

array([[ 5.96,  9.26,  5.02,  0.21,  1.45, -0.34, -0.99, -0.75, -0.36,
        -0.82],
       [ 3.8 ,  4.43,  2.92,  6.02,  9.11, -0.92, -0.47, -0.6 , -1.  ,
        -0.32]])

## Concatenación de Series con Pandas

In [9]:
s1 = pd.Series( x1[0,:] , index=['a','b','c','d','e'] )
s1

a   5.96
b   9.26
c   5.02
d   0.21
e   1.45
dtype: float64

In [10]:
s2 = pd.Series( x2[0,:] , index=['c','d','e','f','g'] )
s2

c   -0.34
d   -0.99
e   -0.75
f   -0.36
g   -0.82
dtype: float64

In [11]:
# Concatenación de Series en dirección vertical
pd.concat([s1,s2] , axis=0)

a    5.96
b    9.26
c    5.02
d    0.21
e    1.45
c   -0.34
d   -0.99
e   -0.75
f   -0.36
g   -0.82
dtype: float64

In [12]:
# Concatenación de Series en dirección horizontal
pd.concat([s1,s2] , axis=1)

0     1
a 5.96   NaN
b 9.26   NaN
c 5.02 -0.34
d 0.21 -0.99
e 1.45 -0.75
f  NaN -0.36
g  NaN -0.82

In [13]:
# reseteamos los nombres de los indices:
s1.reset_index(drop=True)

0   5.96
1   9.26
2   5.02
3   0.21
4   1.45
dtype: float64

In [14]:
# reseteamos los nombres de los indices:
s2.reset_index(drop=True)

0   -0.34
1   -0.99
2   -0.75
3   -0.36
4   -0.82
dtype: float64

In [15]:
# Reseteamos índices y después concatenamos:
pd.concat( [s1.reset_index(drop=True) , s2.reset_index(drop=True)], axis = 1)

0     1
0 5.96 -0.34
1 9.26 -0.99
2 5.02 -0.75
3 0.21 -0.36
4 1.45 -0.82

## Concatenación de DataFrames con Pandas

In [16]:
df1 = pd.DataFrame( np.random.rand(3,2)*10 , columns = ['a','b'])
df1

a    b
0 6.27 8.69
1 1.11 8.28
2 9.98 6.42

In [17]:
df2 = pd.DataFrame( np.random.rand(3,2)*(-1) , columns = ['a','b'], index =[2,3,4])
df2

a     b
2 -0.94 -0.22
3 -0.49 -0.09
4 -0.89 -0.40

In [18]:
# Concatena DataFrames en dirección vertical (se repiten indices)
pd.concat( [df1, df2], axis = 0)

a     b
0  6.27  8.69
1  1.11  8.28
2  9.98  6.42
2 -0.94 -0.22
3 -0.49 -0.09
4 -0.89 -0.40

In [19]:
# Concatena DataFrames en dirección horizontal (se repiten columnas)
pd.concat( [df1, df2], axis = 1)

a    b     a     b
0 6.27 8.69   NaN   NaN
1 1.11 8.28   NaN   NaN
2 9.98 6.42 -0.94 -0.22
3  NaN  NaN -0.49 -0.09
4  NaN  NaN -0.89 -0.40

In [20]:
# Obtenemos la intersección de ambos DataFrames
pd.concat( [df1, df2], axis = 1, join='inner')

a    b     a     b
2 9.98 6.42 -0.94 -0.22

In [21]:
# reseteamos los nombres de los indices:
df1.reset_index(drop=True)

a    b
0 6.27 8.69
1 1.11 8.28
2 9.98 6.42

In [22]:
# reseteamos los nombres de los indices:
df2.reset_index(drop=True)

a     b
0 -0.94 -0.22
1 -0.49 -0.09
2 -0.89 -0.40

In [23]:
# Reseteamos índices y después concatenamos:
pd.concat( [df1.reset_index(drop=True) , df2.reset_index(drop=True)], axis = 1)

a    b     a     b
0 6.27 8.69 -0.94 -0.22
1 1.11 8.28 -0.49 -0.09
2 9.98 6.42 -0.89 -0.40

In [25]:
df1

a    b
0 6.27 8.69
1 1.11 8.28
2 9.98 6.42

In [26]:
df2

a     b
2 -0.94 -0.22
3 -0.49 -0.09
4 -0.89 -0.40

In [24]:
# Concatenamos con la función '.append()'
# '.append()' concatena en dirección vertical
df1.append(df2)

a     b
0  6.27  8.69
1  1.11  8.28
2  9.98  6.42
2 -0.94 -0.22
3 -0.49 -0.09
4 -0.89 -0.40